# Generated by Django 3.2.6 on 2021-08-13 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloggerapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
